name: Node.js Package

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with GitHub package registry
        run: dotnet nuget add source --username begonaguereca --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/begonaguereca/index.json"
      - name: DotNet restore
        run: nuget install OctocatApp -Version 1.0.0
